# Generated by Django 4.2.3 on 2023-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube",
            name="url",
            field=models.URLField(default="Insert a Youtube Link", null=True),
        ),
    ]
